In [1]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

**Tensors**


Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [2]:
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.7753e+28, 1.6085e+19, 1.7589e+22],
        [2.8926e+12, 7.5338e+28, 7.6286e-19],
        [7.1758e+22, 1.4603e-19, 1.8888e+31],
        [4.9656e+28, 4.5439e+30, 1.6907e-01],
        [1.7743e+28, 1.3458e-14, 3.7772e-39]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.2078, 0.0204, 0.8868],
        [0.4860, 0.4653, 0.2769],
        [0.9918, 0.5047, 0.1539],
        [0.5736, 0.1267, 0.3685],
        [0.4241, 0.7772, 0.4473]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

So, essentially, **new_ones allows**** you to quickly create a new torch.Tensor** on the **same device** and **data type** as a previously existing tensor (with ones).

ones() serves the purpose of creating a torch.Tensor from scratch (filled with ones).

In [7]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype!
print(x)                                   # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0754, -0.0705,  1.6942],
        [-0.3799,  1.2362, -1.2539],
        [-0.1493, -0.7423,  0.3148],
        [-0.4323, -1.4072,  0.8729],
        [-1.3493, -0.7458, -0.5782]])


Get its size (same as shape):

In [8]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

**Operations**

There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

**Addition**

In [9]:
# Syntax 1
y = torch.rand(5,3)
print(x + y)

# Syntax 2
print(torch.add(x,y))

# Syntax 3
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

# Syntax 4
y.add_(x)
print(y)

tensor([[ 0.5389,  0.8947,  2.2153],
        [ 0.4140,  1.7779, -0.9623],
        [ 0.3957,  0.1727,  1.1088],
        [-0.1182, -1.3621,  1.3452],
        [-0.4758, -0.2795, -0.4693]])
tensor([[ 0.5389,  0.8947,  2.2153],
        [ 0.4140,  1.7779, -0.9623],
        [ 0.3957,  0.1727,  1.1088],
        [-0.1182, -1.3621,  1.3452],
        [-0.4758, -0.2795, -0.4693]])
tensor([[ 0.5389,  0.8947,  2.2153],
        [ 0.4140,  1.7779, -0.9623],
        [ 0.3957,  0.1727,  1.1088],
        [-0.1182, -1.3621,  1.3452],
        [-0.4758, -0.2795, -0.4693]])
tensor([[ 0.5389,  0.8947,  2.2153],
        [ 0.4140,  1.7779, -0.9623],
        [ 0.3957,  0.1727,  1.1088],
        [-0.1182, -1.3621,  1.3452],
        [-0.4758, -0.2795, -0.4693]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [10]:
print(x[:,1])

tensor([-0.0705,  1.2362, -0.7423, -1.4072, -0.7458])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [11]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.shape, y.shape, z.shape)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [12]:
x = torch.randn(1)
print(x)
print(x.item()) # If the tensor has more than 1 element "only one element tensors can be converted" error is thrown

tensor([-1.4851])
-1.4851492643356323


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described [here](https://pytorch.org/docs/torch)

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [13]:
a = torch.ones(5, dtype=torch.float64)
print(a)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [14]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [15]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64) [2. 2. 2. 2. 2.]


**Converting NumPy Array to Torch Tensor**

See how changing the np array changed the Torch Tensor automatically



In [16]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.

We will use ``torch.device`` objects to move tensors in and out of GPU

In [17]:
if torch.cuda.is_available(): # Check CUDA
    device = torch.device("cuda") # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device) # or just .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) # to can also change dtype

tensor([1.5377], device='cuda:0')
tensor([1.5377], dtype=torch.float64)
